apiVersion: v1
kind: ConfigMap
metadata:
  name: spark-worker-config
  namespace: spark-ns
data:
  SPARK_WORKER_CORES: "1"
  SPARK_WORKER_MEMORY: "1G"
  SPARK_DRIVER_MEMORY: "1G"
  SPARK_EXECUTOR_MEMORY: "1G"
