## SOLUTION 1: USING CLUSTER-IP | localhost:8081
apiVersion: v1
kind: Service
metadata:
  name: spark-master-clusterip-svc
  namespace: spark-ns
spec:
  type: ClusterIP
  selector:
    app: spark-master
  ports:
  - port: 2345
    protocol: TCP
    targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spark-ingress
  namespace: spark-ns
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: spark-master-clusterip-svc
            port:
              number: 2345
---
## SOLUTION 2: USING NODEPORT | localhost:8082
apiVersion: v1
kind: Service
metadata:
  name: spark-master-nodeport-svc
  namespace: spark-ns
spec:
  type: NodePort
  selector:
    app: spark-master
  ports:
  - name: spark-master-port
    protocol: TCP
    nodePort: 30080
    port: 1234
    targetPort: 8080 # replace with 4040 to get the spark-UI
