
apiVersion: v1 # Includes the Service for lazyness
kind: Service
metadata:
  name: spark-worker-svc
  namespace: spark-ns
  labels:
    app: spark-worker-app
spec:
  clusterIP: None
  selector:
    app: spark-worker
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: spark-worker-ss
  namespace: spark-ns
spec:
  serviceName: spark-worker-svc
  replicas: 4
  selector:
    matchLabels:
      app: spark-worker
  template:
    metadata:
      labels:
        app: spark-worker
    spec:
      initContainers:
        - name: wait-for-master
          image: busybox
          command: ['sh', '-c', 'until ping -c 1 spark-master-svc; do sleep 1; done']
      volumes:
      - name: spark-worker-volume
        persistentVolumeClaim:
          claimName: spark-pvc
      containers:
      - name: spark-worker
        image: tryfonm/spark-node
        env:
        - name: SPARK_WORKLOAD
          value: worker
        envFrom:
        - configMapRef:
            name: spark-worker-config
        # ports:
        # - containerPort: 7078
        volumeMounts:
        - name: spark-worker-volume
          mountPath: /shared
        command:
        - "sh"
        - "-c"
        - |
          /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker \
          spark-master-svc:7077
