
apiVersion: v1 # Includes the Service for lazyness
kind: Service
metadata:
  name: spark-master-svc
  labels:
    app: spark-master-app
spec:
  ports:
  - port: 7077
    name: spark-master-port
  clusterIP: None
  selector:
    app: spark-master
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: spark-master-ss
  namespace: spark-ns
spec:
  serviceName: spark-master-svc
  replicas: 1
  selector:
    matchLabels:
      app: spark-master
  template:
    metadata:
      labels:
        app: spark-master
    spec:
      volumes:
      - name: spark-master-volume
        persistentVolumeClaim:
          claimName: spark-pvc
      containers:
      - name: spark-master
        image: tryfonm/spark-node
        env:
        - name: SPARK_WORKLOAD
          value: master
        ports:
        - containerPort: 7077
        volumeMounts:
        - name: spark-master-volume
          mountPath: /shared
        command: 
          - "sh"
          - "-c"
          - |
            rm -rf /shared/.config && 
            echo SPARK_MASTER=spark://$(hostname -i):7077 >> /shared/.config &&
            /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
            --ip spark-master-svc \
            --port 7077 \
            --webui-port 8080
