apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-master-dep
  namespace: spark-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-master
  template:
    metadata:
      labels:
        app: spark-master

    spec:

      volumes:
      - name: spark-master-volume
        persistentVolumeClaim:
          claimName: spark-pvc

      containers:
      - name: spark-master
        image: apache/spark:latest
        env:
        - name: SPARK_WORKLOAD
          value: "master"
        ports:
        - containerPort: 8080
        - containerPort: 7077
        - containerPort: 4040
        volumeMounts:
        - name: spark-master-volume
          mountPath: /opt/spark/work-dir/shared-spark
        command:
        - "sh"
        - "-c"
        - |
          echo SPARK_MASTER=$(hostname -i) >> /opt/spark/work-dir/shared-spark/my-spark-config &&
          export SPARK_MASTER=$(hostname -i) &&
          exec /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
          --ip $SPARK_MASTER
          --port 7077
          --webui-port 8080 &&
      restartPolicy: Always
