apiVersion: v1
kind: Service
metadata:
  name: spark-history-server-svc
  namespace: spark-ns
spec:
  type: ClusterIP
  selector:
    app: spark-history-server
  ports:
  - port: 2345
    protocol: TCP
    targetPort: 18080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spark-ingress
  namespace: spark-ns
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: spark-history-server-svc
            port:
              number: 2345
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-history-server-dep
  namespace: spark-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-history-server
  template:
    metadata:
      labels:
        app: spark-history-server
    spec:
      volumes:
      - name: spark-history-server-volume
        persistentVolumeClaim:
          claimName: spark-logs-pvc
      containers:
      - name: spark-history-server
        image: tryfonm/spark-node
        ports:
        - containerPort: 18080
        volumeMounts:
        - name: spark-history-server-volume
          mountPath: /opt/spark/event-logs
        command: ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.history.HistoryServer"]
